//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int ID { get; set; }
        public int ID_class { get; set; }
        public int ID_lesson { get; set; }
        public int ID_classroom { get; set; }
        public int ID_teacher { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Classroom Classroom { get; set; }
        public virtual Lesson Lesson { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
